-- SQL para actualizar productos con imágenes reales

UPDATE products SET images = '{"previews":["/images/products/pincel-persianero-galgo/pincel-persianero-galgo-bg-1.jpg","/images/products/pincel-persianero-galgo/pincel-persianero-galgo-bg-2.jpg"],"thumbnails":["/images/products/pincel-persianero-galgo/pincel-persianero-galgo-sm-1.jpg","/images/products/pincel-persianero-galgo/pincel-persianero-galgo-sm-2.jpg"]}' WHERE slug LIKE '%pincel-persianero-galgo%';
UPDATE products SET images = '{"previews":["/images/products/rodillo-elefante-galgo/rodillo-elefante-galgo-bg-1.jpg","/images/products/rodillo-elefante-galgo/rodillo-elefante-galgo-bg-2.jpg"],"thumbnails":["/images/products/rodillo-elefante-galgo/rodillo-elefante-galgo-sm-1.jpg","/images/products/rodillo-elefante-galgo/rodillo-elefante-galgo-sm-2.jpg"]}' WHERE slug LIKE '%rodillo-elefante-galgo%';
UPDATE products SET images = '{"previews":["/images/products/plavipint-techos-plavicon/plavipint-techos-plavicon-bg-1.jpg","/images/products/plavipint-techos-plavicon/plavipint-techos-plavicon-bg-2.jpg"],"thumbnails":["/images/products/plavipint-techos-plavicon/plavipint-techos-plavicon-sm-1.jpg","/images/products/plavipint-techos-plavicon/plavipint-techos-plavicon-sm-2.jpg"]}' WHERE slug LIKE '%plavipint-techos-plavicon%';
UPDATE products SET images = '{"previews":["/images/products/membrana-performa-plavicon/membrana-performa-plavicon-bg-1.jpg","/images/products/membrana-performa-plavicon/membrana-performa-plavicon-bg-2.jpg"],"thumbnails":["/images/products/membrana-performa-plavicon/membrana-performa-plavicon-sm-1.jpg","/images/products/membrana-performa-plavicon/membrana-performa-plavicon-sm-2.jpg"]}' WHERE slug LIKE '%membrana-performa-plavicon%';
UPDATE products SET images = '{"previews":["/images/products/latex-frentes-plavicon/latex-frentes-plavicon-bg-1.jpg","/images/products/latex-frentes-plavicon/latex-frentes-plavicon-bg-2.jpg"],"thumbnails":["/images/products/latex-frentes-plavicon/latex-frentes-plavicon-sm-1.jpg","/images/products/latex-frentes-plavicon/latex-frentes-plavicon-sm-2.jpg"]}' WHERE slug LIKE '%latex-frentes-plavicon%';
UPDATE products SET images = '{"previews":["/images/products/latex-interior-plavicon/latex-interior-plavicon-bg-1.jpg","/images/products/latex-interior-plavicon/latex-interior-plavicon-bg-2.jpg"],"thumbnails":["/images/products/latex-interior-plavicon/latex-interior-plavicon-sm-1.jpg","/images/products/latex-interior-plavicon/latex-interior-plavicon-sm-2.jpg"]}' WHERE slug LIKE '%latex-interior-plavicon%';
UPDATE products SET images = '{"previews":["/images/products/cielorraso-plavicon/cielorraso-plavicon-bg-1.jpg","/images/products/cielorraso-plavicon/cielorraso-plavicon-bg-2.jpg"],"thumbnails":["/images/products/cielorraso-plavicon/cielorraso-plavicon-sm-1.jpg","/images/products/cielorraso-plavicon/cielorraso-plavicon-sm-2.jpg"]}' WHERE slug LIKE '%cielorraso-plavicon%';
UPDATE products SET images = '{"previews":["/images/products/latex-muros-plavicon/latex-muros-plavicon-bg-1.jpg","/images/products/latex-muros-plavicon/latex-muros-plavicon-bg-2.jpg"],"thumbnails":["/images/products/latex-muros-plavicon/latex-muros-plavicon-sm-1.jpg","/images/products/latex-muros-plavicon/latex-muros-plavicon-sm-2.jpg"]}' WHERE slug LIKE '%latex-muros-plavicon%';
UPDATE products SET images = '{"previews":["/images/products/recuplast-interior-sinteplast/recuplast-interior-sinteplast-bg-1.jpg","/images/products/recuplast-interior-sinteplast/recuplast-interior-sinteplast-bg-2.jpg"],"thumbnails":["/images/products/recuplast-interior-sinteplast/recuplast-interior-sinteplast-sm-1.jpg","/images/products/recuplast-interior-sinteplast/recuplast-interior-sinteplast-sm-2.jpg"]}' WHERE slug LIKE '%recuplast-interior-sinteplast%';
UPDATE products SET images = '{"previews":["/images/products/recuplast-bano-sinteplast/recuplast-bano-sinteplast-bg-1.jpg","/images/products/recuplast-bano-sinteplast/recuplast-bano-sinteplast-bg-2.jpg"],"thumbnails":["/images/products/recuplast-bano-sinteplast/recuplast-bano-sinteplast-sm-1.jpg","/images/products/recuplast-bano-sinteplast/recuplast-bano-sinteplast-sm-2.jpg"]}' WHERE slug LIKE '%recuplast-bano-sinteplast%';
UPDATE products SET images = '{"previews":["/images/products/poximix-poxipol/poximix-poxipol-bg-1.jpg","/images/products/poximix-poxipol/poximix-poxipol-bg-2.jpg"],"thumbnails":["/images/products/poximix-poxipol/poximix-poxipol-sm-1.jpg","/images/products/poximix-poxipol/poximix-poxipol-sm-2.jpg"]}' WHERE slug LIKE '%poximix-poxipol%';
UPDATE products SET images = '{"previews":["/images/products/converlux-petrilac/converlux-petrilac-bg-1.jpg","/images/products/converlux-petrilac/converlux-petrilac-bg-2.jpg"],"thumbnails":["/images/products/converlux-petrilac/converlux-petrilac-sm-1.jpg","/images/products/converlux-petrilac/converlux-petrilac-sm-2.jpg"]}' WHERE slug LIKE '%converlux-petrilac%';
UPDATE products SET images = '{"previews":["/images/products/danzke-petrilac/danzke-petrilac-bg-1.jpg","/images/products/danzke-petrilac/danzke-petrilac-bg-2.jpg"],"thumbnails":["/images/products/danzke-petrilac/danzke-petrilac-sm-1.jpg","/images/products/danzke-petrilac/danzke-petrilac-sm-2.jpg"]}' WHERE slug LIKE '%danzke-petrilac%';
UPDATE products SET images = '{"previews":["/images/products/campbell-petrilac/campbell-petrilac-bg-1.jpg","/images/products/campbell-petrilac/campbell-petrilac-bg-2.jpg"],"thumbnails":["/images/products/campbell-petrilac/campbell-petrilac-sm-1.jpg","/images/products/campbell-petrilac/campbell-petrilac-sm-2.jpg"]}' WHERE slug LIKE '%campbell-petrilac%';
UPDATE products SET images = '{"previews":["/images/products/cinta-papel/cinta-papel-bg-1.jpg","/images/products/cinta-papel/cinta-papel-bg-2.jpg"],"thumbnails":["/images/products/cinta-papel/cinta-papel-sm-1.jpg","/images/products/cinta-papel/cinta-papel-sm-2.jpg"]}' WHERE slug LIKE '%cinta-papel%';
