-- SQL para actualizar productos con placeholders profesionales

UPDATE products SET images = '{"previews": ["/images/products/poximix-interior-05kg-poxipol.jpg"], "thumbnails": ["/images/products/poximix-interior-sm-poxipol.jpg"]}' WHERE slug LIKE '%poximix-interior-05kg-poxipol%';
UPDATE products SET images = '{"previews": ["/images/products/poximix-interior-125kg-poxipol.jpg"], "thumbnails": ["/images/products/poximix-interior-sm-poxipol.jpg"]}' WHERE slug LIKE '%poximix-interior-125kg-poxipol%';
UPDATE products SET images = '{"previews": ["/images/products/poximix-interior-3kg-poxipol.jpg"], "thumbnails": ["/images/products/poximix-interior-sm-poxipol.jpg"]}' WHERE slug LIKE '%poximix-interior-3kg-poxipol%';
UPDATE products SET images = '{"previews": ["/images/products/poximix-interior-5kg-poxipol.jpg"], "thumbnails": ["/images/products/poximix-interior-sm-poxipol.jpg"]}' WHERE slug LIKE '%poximix-interior-5kg-poxipol%';
UPDATE products SET images = '{"previews": ["/images/products/pincel-persianero-n10-galgo.jpg"], "thumbnails": ["/images/products/pincel-persianero-sm-galgo.jpg"]}' WHERE slug LIKE '%pincel-persianero-n10-galgo%';
UPDATE products SET images = '{"previews": ["/images/products/pincel-persianero-n15-galgo.jpg"], "thumbnails": ["/images/products/pincel-persianero-sm-galgo.jpg"]}' WHERE slug LIKE '%pincel-persianero-n15-galgo%';
UPDATE products SET images = '{"previews": ["/images/products/pincel-persianero-n20-galgo.jpg"], "thumbnails": ["/images/products/pincel-persianero-sm-galgo.jpg"]}' WHERE slug LIKE '%pincel-persianero-n20-galgo%';
UPDATE products SET images = '{"previews": ["/images/products/pincel-persianero-n25-galgo.jpg"], "thumbnails": ["/images/products/pincel-persianero-sm-galgo.jpg"]}' WHERE slug LIKE '%pincel-persianero-n25-galgo%';
UPDATE products SET images = '{"previews": ["/images/products/pincel-persianero-n30-galgo.jpg"], "thumbnails": ["/images/products/pincel-persianero-sm-galgo.jpg"]}' WHERE slug LIKE '%pincel-persianero-n30-galgo%';
UPDATE products SET images = '{"previews": ["/images/products/rodillo-22cm-lanar-elefante-galgo.jpg"], "thumbnails": ["/images/products/rodillo-sm-lanar-elefante-galgo.jpg"]}' WHERE slug LIKE '%rodillo-22cm-lanar-elefante-galgo%';
UPDATE products SET images = '{"previews": ["/images/products/plavipint-techos-poliuretanico-10l-plavicon.jpg"], "thumbnails": ["/images/products/plavipint-techos-poliuretanico-sm-plavicon.jpg"]}' WHERE slug LIKE '%plavipint-techos-poliuretanico-10l-plavicon%';
UPDATE products SET images = '{"previews": ["/images/products/plavipint-techos-poliuretanico-20l-plavicon.jpg"], "thumbnails": ["/images/products/plavipint-techos-poliuretanico-sm-plavicon.jpg"]}' WHERE slug LIKE '%plavipint-techos-poliuretanico-20l-plavicon%';
UPDATE products SET images = '{"previews": ["/images/products/latex-frentes-4l-plavicon.jpg"], "thumbnails": ["/images/products/latex-frentes-sm-plavicon.jpg"]}' WHERE slug LIKE '%latex-frentes-4l-plavicon%';
UPDATE products SET images = '{"previews": ["/images/products/latex-interior-4l-plavicon.jpg"], "thumbnails": ["/images/products/latex-interior-sm-plavicon.jpg"]}' WHERE slug LIKE '%latex-interior-4l-plavicon%';
UPDATE products SET images = '{"previews": ["/images/products/cielorraso-1l-plavicon.jpg"], "thumbnails": ["/images/products/cielorraso-sm-plavicon.jpg"]}' WHERE slug LIKE '%cielorraso-1l-plavicon%';
UPDATE products SET images = '{"previews": ["/images/products/latex-muros-4l-plavicon.jpg"], "thumbnails": ["/images/products/latex-muros-sm-plavicon.jpg"]}' WHERE slug LIKE '%latex-muros-4l-plavicon%';
UPDATE products SET images = '{"previews": ["/images/products/recuplast-interior-1l-sinteplast.jpg"], "thumbnails": ["/images/products/recuplast-interior-sm-sinteplast.jpg"]}' WHERE slug LIKE '%recuplast-interior-1l-sinteplast%';
UPDATE products SET images = '{"previews": ["/images/products/recuplast-bano-cocina-1l-sinteplast.jpg"], "thumbnails": ["/images/products/recuplast-bano-cocina-sm-sinteplast.jpg"]}' WHERE slug LIKE '%recuplast-bano-cocina-1l-sinteplast%';
UPDATE products SET images = '{"previews": ["/images/products/cinta-papel-blanca-36mm.jpg"], "thumbnails": ["/images/products/cinta-papel-blanca-36mm.jpg"]}' WHERE slug LIKE '%cinta-papel-blanca-36mm%';
