// ===================================
// PALETA DE COLORES PARA PINTURAS
// Archivo compartido para uso en cliente y servidor
// ===================================

import type { TextureType } from '@/lib/textures/texture-system'

export interface ColorOption {
  id: string
  name: string
  displayName: string
  hex: string
  category: string
  family: string
  isPopular?: boolean
  description?: string
  textureType?: TextureType  // Tipo de textura visual a aplicar
}

export const PAINT_COLORS: ColorOption[] = [
  // ===================================
  // COLORES PARA PRODUCTOS DE MADERA
  // ===================================
  // Tonos naturales y cálidos específicos para productos de madera
  {
    id: 'blanco-puro',
    name: 'blanco-puro',
    displayName: 'Blanco Puro',
    hex: '#F5F5F5',
    category: 'Madera',
    family: 'Blancos',
    isPopular: true,
    description: 'Blanco clásico para madera',
    textureType: 'wood',
  },
  {
    id: 'crema',
    name: 'crema',
    displayName: 'Crema',
    hex: '#F5F5DC',
    category: 'Madera',
    family: 'Blancos',
    isPopular: true,
    description: 'Tono cremoso natural',
    textureType: 'wood',
  },
  {
    id: 'cedro',
    name: 'cedro',
    displayName: 'Cedro',
    hex: '#C26A2B',
    category: 'Madera',
    family: 'Marrones',
    isPopular: true,
    description: 'Tono natural de cedro',
    textureType: 'wood',
  },
  {
    id: 'caoba',
    name: 'caoba',
    displayName: 'Caoba',
    hex: '#8E3B1F',
    category: 'Madera',
    family: 'Marrones',
    isPopular: true,
    description: 'Marrón rojizo elegante',
    textureType: 'wood',
  },
  {
    id: 'roble',
    name: 'roble',
    displayName: 'Roble',
    hex: '#C7955B',
    category: 'Madera',
    family: 'Marrones',
    isPopular: true,
    description: 'Tono clásico de roble',
    textureType: 'wood',
  },
  {
    id: 'roble-britanico',
    name: 'roble-britanico',
    displayName: 'Roble Británico',
    hex: '#8B4513',
    category: 'Madera',
    family: 'Marrones',
    isPopular: true,
    description: 'Marrón clásico de roble',
    textureType: 'wood',
  },
  {
    id: 'roble-oscuro-satinado',
    name: 'roble-oscuro-satinado',
    displayName: 'Roble Oscuro Satinado',
    hex: '#654321',
    category: 'Madera',
    family: 'Marrones',
    isPopular: true,
    description: 'Roble oscuro con acabado satinado',
    textureType: 'wood',
  },
  {
    id: 'nogal',
    name: 'nogal',
    displayName: 'Nogal',
    hex: '#5C3A1A',
    category: 'Madera',
    family: 'Marrones',
    description: 'Marrón profundo de nogal',
    textureType: 'wood',
  },
  {
    id: 'pino',
    name: 'pino',
    displayName: 'Pino',
    hex: '#E5B57E',
    category: 'Madera',
    family: 'Marrones',
    description: 'Tono claro amarillento típico del pino',
    textureType: 'wood',
  },
  {
    id: 'natural',
    name: 'natural',
    displayName: 'Natural',
    hex: '#DEB887',
    category: 'Madera',
    family: 'Marrones',
    description: 'Tono madera natural',
    textureType: 'wood',
  },
  {
    id: 'cristal',
    name: 'cristal',
    displayName: 'Cristal',
    hex: '#E8D5B5',
    category: 'Madera',
    family: 'Marrones',
    description: 'Transparente levemente cálido para madera',
    textureType: 'wood',
  },
  {
    id: 'incoloro',
    name: 'incoloro',
    displayName: 'Incoloro',
    hex: 'rgba(255,255,255,0.1)',
    category: 'Madera',
    family: 'Transparentes',
    description: 'Transparente completamente incoloro con brillo',
    textureType: 'transparent',
  },

  // ===================================
  // COLORES PARA PRODUCTOS SINTÉTICOS
  // ===================================
  // Paleta oficial de 17 colores para productos sintéticos
  {
    id: 'aluminio',
    name: 'aluminio',
    displayName: 'Aluminio',
    hex: '#A8A8A8',
    category: 'Sintético',
    family: 'Grises',
    isPopular: true,
    description: 'Gris aluminio metálico',
  },
  {
    id: 'amarillo',
    name: 'amarillo',
    displayName: 'Amarillo',
    hex: '#FFFF00',
    category: 'Sintético',
    family: 'Amarillos',
    isPopular: true,
    description: 'Amarillo puro vibrante',
  },
  {
    id: 'amarillo-mediano',
    name: 'amarillo-mediano',
    displayName: 'Amarillo Mediano',
    hex: '#FFD700',
    category: 'Sintético',
    family: 'Amarillos',
    isPopular: true,
    description: 'Amarillo dorado mediano',
  },
  {
    id: 'azul-marino',
    name: 'azul-marino',
    displayName: 'Azul Marino',
    hex: '#000080',
    category: 'Sintético',
    family: 'Azules',
    isPopular: true,
    description: 'Azul marino profundo',
  },
  {
    id: 'azul-traful',
    name: 'azul-traful',
    displayName: 'Azul Traful',
    hex: '#4682B4',
    category: 'Sintético',
    family: 'Azules',
    isPopular: true,
    description: 'Azul acero traful',
  },
  {
    id: 'bermellon',
    name: 'bermellon',
    displayName: 'Bermellón',
    hex: '#E34234',
    category: 'Sintético',
    family: 'Rojos',
    isPopular: true,
    description: 'Rojo bermellón intenso',
  },
  {
    id: 'rojo-teja',
    name: 'rojo-teja',
    displayName: 'Rojo Teja',
    hex: '#A63A2B',
    category: 'Sintético',
    family: 'Rojos',
    isPopular: true,
    description: 'Rojo teja clásico para exteriores y techos',
  },
  {
    id: 'blanco',
    name: 'blanco',
    displayName: 'Blanco',
    hex: '#FFFFFF',
    category: 'Sintético',
    family: 'Blancos',
    isPopular: true,
    description: 'Blanco puro para sintéticos',
  },
  {
    id: 'gris',
    name: 'gris',
    displayName: 'Gris',
    hex: '#808080',
    category: 'Sintético',
    family: 'Grises',
    isPopular: true,
    description: 'Gris neutro estándar',
  },
  {
    id: 'gris-espacial',
    name: 'gris-espacial',
    displayName: 'Gris Espacial',
    hex: '#696969',
    category: 'Sintético',
    family: 'Grises',
    isPopular: true,
    description: 'Gris espacial oscuro',
  },
  {
    id: 'gris-perla',
    name: 'gris-perla',
    displayName: 'Gris Perla',
    hex: '#C0C0C0',
    category: 'Sintético',
    family: 'Grises',
    isPopular: true,
    description: 'Gris perla claro',
  },
  {
    id: 'marfil',
    name: 'marfil',
    displayName: 'Marfil',
    hex: '#FFFFF0',
    category: 'Sintético',
    family: 'Blancos',
    isPopular: true,
    description: 'Blanco marfil cálido',
  },
  {
    id: 'marron',
    name: 'marron',
    displayName: 'Marrón',
    hex: '#8B4513',
    category: 'Sintético',
    family: 'Marrones',
    isPopular: true,
    description: 'Marrón silla de montar',
  },
  {
    id: 'naranja',
    name: 'naranja',
    displayName: 'Naranja',
    hex: '#FF8C00',
    category: 'Sintético',
    family: 'Naranjas',
    isPopular: true,
    description: 'Naranja vibrante',
  },
  {
    id: 'negro',
    name: 'negro',
    displayName: 'Negro',
    hex: '#000000',
    category: 'Sintético',
    family: 'Negros',
    isPopular: true,
    description: 'Negro puro para sintéticos',
  },
  {
    id: 'tostado',
    name: 'tostado',
    displayName: 'Tostado',
    hex: '#D2B48C',
    category: 'Sintético',
    family: 'Marrones',
    isPopular: true,
    description: 'Beige tostado cálido',
  },
  {
    id: 'verde-ingles',
    name: 'verde-ingles',
    displayName: 'Verde Inglés',
    hex: '#355E3B',
    category: 'Sintético',
    family: 'Verdes',
    isPopular: true,
    description: 'Verde profundo y elegante',
  },
  {
    id: 'verde-noche',
    name: 'verde-noche',
    displayName: 'Verde Noche',
    hex: '#013220',
    category: 'Sintético',
    family: 'Verdes',
    isPopular: true,
    description: 'Verde muy oscuro nocturno',
  },

  // ===================================
  // COLORES GENERALES (NEUTROS)
  // ===================================
  // Blancos y Neutros generales
  {
    id: 'blanco-roto',
    name: 'blanco-roto',
    displayName: 'Blanco Roto',
    hex: '#FEFEFE',
    category: 'Neutros',
    family: 'Blancos',
    description: 'Blanco suave con matiz cálido',
  },
  {
    id: 'gris-perla',
    name: 'gris-perla',
    displayName: 'Gris Perla',
    hex: '#E8E8E8',
    category: 'Neutros',
    family: 'Grises',
    isPopular: true,
  },
  {
    id: 'gris-plata',
    name: 'gris-plata',
    displayName: 'Gris Plata',
    hex: '#C0C0C0',
    category: 'Neutros',
    family: 'Grises',
  },
  {
    id: 'gris-antracita',
    name: 'gris-antracita',
    displayName: 'Gris Antracita',
    hex: '#36454F',
    category: 'Neutros',
    family: 'Grises',
  },
  {
    id: 'cemento',
    name: 'cemento',
    displayName: 'Cemento',
    hex: '#9FA1A3',
    category: 'Neutros',
    family: 'Grises',
    isPopular: true,
    description: 'Gris cemento neutro para exteriores',
  },

  // Azules generales
  {
    id: 'azul-cielo',
    name: 'azul-cielo',
    displayName: 'Azul Cielo',
    hex: '#87CEEB',
    category: 'Fríos',
    family: 'Azules',
    isPopular: true,
    description: 'Azul suave y relajante',
  },
  {
    id: 'azul-turquesa',
    name: 'azul-turquesa',
    displayName: 'Azul Turquesa',
    hex: '#40E0D0',
    category: 'Fríos',
    family: 'Azules',
  },
  {
    id: 'azul-petroleo',
    name: 'azul-petroleo',
    displayName: 'Azul Petróleo',
    hex: '#2F4F4F',
    category: 'Fríos',
    family: 'Azules',
  },

  // Verdes generales
  {
    id: 'verde-menta',
    name: 'verde-menta',
    displayName: 'Verde Menta',
    hex: '#98FB98',
    category: 'Fríos',
    family: 'Verdes',
    isPopular: true,
  },
  {
    id: 'verde-oliva',
    name: 'verde-oliva',
    displayName: 'Verde Oliva',
    hex: '#808000',
    category: 'Fríos',
    family: 'Verdes',
  },
  {
    id: 'verde-bosque',
    name: 'verde-bosque',
    displayName: 'Verde Bosque',
    hex: '#228B22',
    category: 'Fríos',
    family: 'Verdes',
  },
  {
    id: 'verde-salvia',
    name: 'verde-salvia',
    displayName: 'Verde Salvia',
    hex: '#9CAF88',
    category: 'Fríos',
    family: 'Verdes',
  },

  // Rojos y Rosas generales
  {
    id: 'rojo-coral',
    name: 'rojo-coral',
    displayName: 'Rojo Coral',
    hex: '#FF7F50',
    category: 'Cálidos',
    family: 'Rojos',
    isPopular: true,
  },
  {
    id: 'rojo-vino',
    name: 'rojo-vino',
    displayName: 'Rojo Vino',
    hex: '#722F37',
    category: 'Cálidos',
    family: 'Rojos',
  },
  {
    id: 'rosa-empolvado',
    name: 'rosa-empolvado',
    displayName: 'Rosa Empolvado',
    hex: '#DDA0DD',
    category: 'Cálidos',
    family: 'Rosas',
  },
  {
    id: 'rosa-cuarzo',
    name: 'rosa-cuarzo',
    displayName: 'Rosa Cuarzo',
    hex: '#F7CAC9',
    category: 'Cálidos',
    family: 'Rosas',
  },

  // Amarillos y Naranjas generales
  {
    id: 'amarillo-manteca',
    name: 'amarillo-manteca',
    displayName: 'Amarillo Manteca',
    hex: '#FFDB58',
    category: 'Cálidos',
    family: 'Amarillos',
    isPopular: true,
  },
  {
    id: 'amarillo-mostaza',
    name: 'amarillo-mostaza',
    displayName: 'Amarillo Mostaza',
    hex: '#FFDB58',
    category: 'Cálidos',
    family: 'Amarillos',
  },
  {
    id: 'naranja-terracota',
    name: 'naranja-terracota',
    displayName: 'Naranja Terracota',
    hex: '#E2725B',
    category: 'Cálidos',
    family: 'Naranjas',
  },
  {
    id: 'naranja-durazno',
    name: 'naranja-durazno',
    displayName: 'Naranja Durazno',
    hex: '#FFCBA4',
    category: 'Cálidos',
    family: 'Naranjas',
  },

  // Marrones y Tierras generales
  {
    id: 'marron-chocolate',
    name: 'marron-chocolate',
    displayName: 'Marrón Chocolate',
    hex: '#7B3F00',
    category: 'Tierras',
    family: 'Marrones',
  },
  {
    id: 'marron-cafe',
    name: 'marron-cafe',
    displayName: 'Marrón Café',
    hex: '#6F4E37',
    category: 'Tierras',
    family: 'Marrones',
  },
  {
    id: 'beige-arena',
    name: 'beige-arena',
    displayName: 'Beige Arena',
    hex: '#F5F5DC',
    category: 'Tierras',
    family: 'Beijes',
    isPopular: true,
  },
  {
    id: 'ocre-dorado',
    name: 'ocre-dorado',
    displayName: 'Ocre Dorado',
    hex: '#CC7722',
    category: 'Tierras',
    family: 'Ocres',
  },

  // Violetas y Púrpuras generales
  {
    id: 'violeta-lavanda',
    name: 'violeta-lavanda',
    displayName: 'Violeta Lavanda',
    hex: '#E6E6FA',
    category: 'Fríos',
    family: 'Violetas',
  },
  {
    id: 'purpura-real',
    name: 'purpura-real',
    displayName: 'Púrpura Real',
    hex: '#663399',
    category: 'Fríos',
    family: 'Violetas',
  },

  // Negros generales
  {
    id: 'negro-carbon',
    name: 'negro-carbon',
    displayName: 'Negro Carbón',
    hex: '#36454F',
    category: 'Neutros',
    family: 'Negros',
  },
  {
    id: 'negro-mate',
    name: 'negro-mate',
    displayName: 'Negro Mate',
    hex: '#000000',
    category: 'Neutros',
    family: 'Negros',
  },
]
