name: Deploy Storybook

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/components/**'
      - 'src/stories/**'
      - '.storybook/**'
      - 'docs/design-system/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/components/**'
      - 'src/stories/**'
      - '.storybook/**'
      - 'docs/design-system/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Storybook
        run: npm run build-storybook
        env:
          NODE_ENV: production
          
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          destination_dir: storybook
          
      - name: Deploy Preview to Vercel
        if: github.event_name == 'pull_request'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./storybook-static
          scope: ${{ secrets.VERCEL_ORG_ID }}
          
      - name: Comment PR with Storybook URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('📚 Storybook Preview')
            );
            
            const body = `## 📚 Storybook Preview
            
            ✅ Storybook has been deployed successfully!
            
            **🔗 Preview URL**: [View Storybook](https://pinteya-ecommerce-storybook.vercel.app)
            
            ### 🧩 Components Updated
            - Design System components
            - Stories and documentation
            - Interactive examples
            
            ### 🎯 What to Review
            - [ ] Component variants and states
            - [ ] Accessibility compliance
            - [ ] Mobile responsiveness
            - [ ] Documentation accuracy
            
            ---
            *This comment will be updated on each push to this PR.*`;
            
            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }
            
      - name: Run Visual Regression Tests
        if: github.event_name == 'pull_request'
        run: |
          npm run test:visual || true
        env:
          STORYBOOK_URL: https://pinteya-ecommerce-storybook.vercel.app
          
      - name: Upload Storybook Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: storybook-static/
          retention-days: 30
          
  accessibility-audit:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run Accessibility Tests
        run: |
          npm run test:a11y || true
        env:
          STORYBOOK_URL: https://pinteya-ecommerce-storybook.vercel.app
          
      - name: Comment Accessibility Results
        uses: actions/github-script@v7
        with:
          script: |
            const body = `## ♿ Accessibility Audit Results
            
            ✅ Accessibility tests completed for Storybook components.
            
            ### 🎯 WCAG 2.1 AA Compliance
            - [ ] Color contrast ratios
            - [ ] Keyboard navigation
            - [ ] Screen reader compatibility
            - [ ] Focus management
            
            ### 📊 Results Summary
            - **Components tested**: All Design System components
            - **Violations found**: Check detailed logs
            - **Compliance level**: WCAG 2.1 AA target
            
            ---
            *Accessibility is a core principle of the Pinteya Design System.*`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
            
  performance-audit:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.12.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ github.sha }}
          LHCI_BUILD_CONTEXT__COMMIT_TIME: ${{ github.event.head_commit.timestamp }}
          
  notify-success:
    runs-on: ubuntu-latest
    needs: [build-and-deploy, accessibility-audit, performance-audit]
    if: always() && github.ref == 'refs/heads/main'
    
    steps:
      - name: Notify Success
        uses: actions/github-script@v7
        with:
          script: |
            console.log('🎉 Storybook deployed successfully to production!');
            console.log('📚 URL: https://santiagoXOR.github.io/pinteya-ecommerce/storybook/');
            console.log('🎨 Design System documentation is now live.');
            
      - name: Create Release Comment
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: latestRelease } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            }).catch(() => ({ data: null }));
            
            if (latestRelease) {
              const body = `## 📚 Storybook Updated
              
              The Design System documentation has been updated and deployed:
              
              **🔗 Live Storybook**: [View Documentation](https://santiagoXOR.github.io/pinteya-ecommerce/storybook/)
              
              ### 🆕 What's New
              - Updated component documentation
              - Latest design tokens
              - Interactive examples
              - Accessibility guidelines
              
              ---
              *Design System Pinteya - Mobile-first e-commerce components*`;
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: latestRelease.id,
                body: body
              });
            }
